---
- hosts: "{{ target | default('all') }}"
  become: True
  roles:
    - { role: pi-init, tags: init }
    - { role: pi-common, tags: common }
    - { role: pi-docker, tags: docker }
    - { role: atosatto.docker-swarm, 
        docker_dependencies: [ ],
        tags: swarm }
