---
- hosts: "{{ host | default('localhost') }}"
  sudo: True
  gather_facts: false
  tasks:
      - name: Install apt packages
        apt: name={{ item }} state=installed
        with_items:
            - wakeonlan
            - python-setuptools
            - python-dev
            - tmux
            - znc
            - mosh
            - ssh
            - git
            - python-pip
            - lsof

      - name: install pip packages
        pip: name={{ item }}
        with_items:
            - ouimeaux # wemo web interface
              
      - name: git repos
        git: repo={{ item.url }} dest={{ item.dest }} 
        # defaults recursive=yes update=yes
        with_items:
          - { url: 'https://github.com/rothgar/dotfiles/', dest: '/home/pi/.dotfiles' }
