---
- hosts: "{{ host | default('localhost') }}"
  sudo: True
  gather_facts: false
  tasks:
      - name: Install apt packages
        apt: name={{ item }} state=latest
        with_items:
            - git
            - lsof
            - mosh
            - python-dev
            - python-pip
            - python-setuptools
            - ssh
            - tmux
            - wakeonlan
            - znc

      - name: git repos
        git: repo={{ item.url }} dest={{ item.dest }} 
        # defaults recursive=yes update=yes
        with_items:
          - { url: 'https://github.com/rothgar/dotfiles/', dest: '/home/pi/.dotfiles' }
        tags: dotfiles
