---
- hosts: "{{ target | default('all') }}"
  become: True
  gather_facts: false
  tasks:
    - apt: name=rpi-update state=latest update_cache=yes cache_valid_time=3600

    - name: Update firmware
      command: /usr/bin/rpi-update

    - name: Expand rootfs
      command: /usr/bin/raspi-config --expand-rootfs

    - hostname: name={{ inventory_hostname }}

    - name: restart machine
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
    
    - name: waiting for server to come back
      local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
      become: false
    
    ### SSH settings
    - name: Add identity key to authorized keys on host
      authorized_key: user="{{ ssh_user }}"
        key="{{ lookup('file', ssh_identity_key) }}"
      register: add_identity_key
      when: ssh_identity_key is defined and ssh_user is defined
      tags:
        - ssh
    
    - name: Disable empty password login
      lineinfile: dest={{ sshd_config }} regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"
      notify: restart sshd
      tags:
        - ssh
    
    - name: Disable remote root login
      lineinfile: dest={{ sshd_config }} regexp="^#?PermitRootLogin" line="PermitRootLogin no"
      notify: restart sshd
      tags:
        - ssh
    
    - name: Disable password login
      lineinfile: dest={{ sshd_config }} regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
      when: add_identity_key|success and not add_identity_key|skipped
      notify: restart sshd
      tags:
        - ssh

    - name: Change pi user password
      user: name=pi update_password=always
        password="{{ lookup('password', 'credentials/pi/password.txt encrypt=md5_crypt') }}"
    
    - name: Add docker repo
      apt_repository: repo="deb [arch=armhf] https://apt.dockerproject.org/repo raspbian-jessie main" state=present
    
    - name: Install apt packages
      apt: name={{ item }} state=latest
      with_items:
          - docker-engine
          - git
          - lsof
          - mosh
          - python-dev
          - python-pip
          - python-setuptools
          - ssh
          - tmux
          - wakeonlan
          - znc
      tags:
        - packages
    
    - name: Start docker service
      service: name=docker state=started enabled=yes

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
