---
# tasks file for pi-init
- name: Install required packages
  apt: name="{{ item }}" state=installed allow_unauthenticated=yes
    update_cache=yes cache_valid_time=3600
  with_items:
    - rpi-update
    - apt-transport-https
    - debian-archive-keyring
  tags:
    - packages

- name: Upgrade system
  apt: upgrade=dist
  tags:
    - packages

- name: Update firmware
  command: /usr/bin/rpi-update
  register: firmware
  changed_when: firmware.rc != 0

- name: Check rootfs size
  shell: "/sbin/parted /dev/mmcblk0 unit '%' print free | grep 'Free Space' | tail -n1 | awk '{print $3}' | awk -F'.' '{print $1}'"
  register: rootfs
  changed_when: False
  tags:
    - rootfs

- name: Expand rootfs
  command: /usr/bin/raspi-config --expand-rootfs
  register: disk_expanded
  when: rootfs.stdout|int > 1
  tags:
    - rootfs

- hostname: name={{ inventory_hostname }}
  register: hostname

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  register: rebooting
  when: hostname|changed or rootfs.stdout|int > 1 or firmware.stdout.find('already up to date') == -1

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }}
    state=started delay=30 timeout=300
  when: rebooting|changed
  become: false
