---
# tasks file for pi-common
### SSH settings
- name: Add identity key to authorized keys on host
  authorized_key: user="{{ ssh_user }}"
    key="{{ lookup('file', ssh_identity_key) }}"
  register: add_identity_key
  when: ssh_identity_key is defined and ssh_user is defined
  tags:
    - ssh

- name: Disable empty password login
  lineinfile: dest={{ sshd_config }} regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"
  notify: restart sshd
  tags:
    - ssh

- name: Disable remote root login
  lineinfile: dest={{ sshd_config }} regexp="^#?PermitRootLogin" line="PermitRootLogin no"
  notify: restart sshd
  tags:
    - ssh

- name: Disable password login
  lineinfile: dest={{ sshd_config }} regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
  when: add_identity_key|success and not add_identity_key|skipped
  notify: restart sshd
  tags:
    - ssh

- name: Change pi user password
  user: name=pi update_password=always
    password="{{ lookup('password', 'credentials/pi/password.txt encrypt=md5_crypt') }}"

- name: Install apt packages
  apt: name={{ item }} state=latest
    update_cache=yes
  with_items:
      - docker-engine
      - docker-compose
      - git
      - lsof
      - mosh
      - python-pip
      - ssh
      - tmux
      - vim
  tags:
    - packages
